### ISSUE TITLE
Parsing Failure for IP Address URLs

### ISSUE THREAD

**Issue by Alt3rmis** [Dolov/chrome-best-cookier#2]
I encountered an issue with the Chrome extension when it tries to read and display cookies from websites accessed via IP addresses instead of domain names. The extension fails to parse cookies correctly for these IP address URLs. 

**Steps to Reproduce**:
1. Install the Chrome extension.
2. Navigate to a website using an IP address (e.g., https://123.45.67.89).
3. Attempt to read the cookies for this website usiang the extension.

**Expected Behavior**:
The extension should correctly parse and display cookies for websites accessed via IP addresses.

**Actual Behavior**:
The extension fails to parse cookies for IP address URLs and does not display them correctly

**Comment by Dolov** [comment]
[fix](https://github.com/Dolov/chrome-best-cookier/commit/8ce36c18d03938cf6e6034961cd009f439b14050)

Waiting for publish
