### ISSUE TITLE
隐私问题

### ISSUE THREAD

**Issue by Xiaosesh** [Dolov/chrome-best-cookier#3]
使用这个插件管理我的cookier数据，会被哪些人看到，他们会利用嘛

**Comment by Dolov** [comment]
> 使用这个插件管理我的cookier数据，会被哪些人看到，他们会利用嘛

1. cookie 都在插件内部管理，在你浏览器本地存储，不会上传云端，不会恶意收集
2. 源码完全开源，可以自行构建，对前端或者有开发经验的工程师很简单
