### ISSUE TITLE
有压缩版吗？

### ISSUE THREAD

**Issue by AY-Front** [Dolov/chrome-best-cookier#4]

**Comment by Dolov** [comment]
> _No description provided._

[chrome-mv3-prod.zip](https://github.com/user-attachments/files/15929488/chrome-mv3-prod.zip)

**Comment by Dolov** [comment]
> _No description provided._

1. 进入 chrome://extensions/
2. 打开开发者模式
3. 加载已解压的扩展程序

**Comment by AY-Front** [comment]
好的 谢谢

**Comment by AY-Front** [comment]
> > _No description provided._
> 
> 1. 进入 chrome://extensions/
> 2. 打开开发者模式
> 3. 加载已解压的扩展程序

好的，谢谢
