### ISSUE TITLE
新增cookie复制为header-string格式到剪切板

### ISSUE THREAD

**Issue by ChenDY2233** [Dolov/chrome-best-cookier#5]
导出功能，新增复制 header string 格式到剪切板，而不是导出下载一个文件到本地磁盘

![image](https://github.com/Dolov/chrome-best-cookier/assets/39426660/bcba5c73-9381-4436-8c46-0d6461fdcc86)

**Comment by Dolov** [comment]
<img width="399" alt="image" src="https://github.com/Dolov/chrome-best-cookier/assets/19704420/eb29215e-8335-4782-9157-af5e63ac58d1">
加上一个复制类型的选择

**Comment by Dolov** [comment]
> 导出功能，新增复制 header string 格式到剪切板，而不是导出下载一个文件到本地磁盘
> 
> ![image](https://private-user-images.githubusercontent.com/39426660/344110808-bcba5c73-9381-4436-8c46-0d6461fdcc86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1OTI5MzksIm5iZiI6MTcxOTU5MjYzOSwicGF0aCI6Ii8zOTQyNjY2MC8zNDQxMTA4MDgtYmNiYTVjNzMtOTM4MS00NDM2LThjNDYtMGQ2NDYxZmRjYzg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDE2MzcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhM2FjOGExNTM4OWYwNDM4N2M3NWVhOGJkZjhiNmJjZGQ5MDJiNzAxODBmY2RkNThkMWM4ZjU5NjcwNjk4NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ok7KtVY6Mg2tgBXIqxKRyrd-VjfIwFR-oEG0h22Jp7M)

<img width="399" alt="image" src="https://github.com/Dolov/chrome-best-cookier/assets/19704420/ae118813-6776-474c-8b63-70c8a55bd377">
加上一个复制类型的选择
