### ISSUE TITLE
Privacy and security issues. 隐私安全问题

### ISSUE THREAD

**Issue by startle09** [Dolov/chrome-best-cookier#7]
你好，chrome store 发布的版本更新于2024-11-21，但是源码最后更新于2024-09-20，请问商店版本和开源版本有什么区别？

Hello, the version released on the Chrome Store was updated on 2024-11-21, but the source code was last updated on 2024-09-20. What is the difference between the store version and the open-source version?

**Comment by Dolov** [comment]
> 你好，chrome store 发布的版本更新于2024-11-21，但是源码最后更新于2024-09-20，请问商店版本和开源版本有什么区别？
> 
> Hello, the version released on the Chrome Store was updated on 2024-11-21, but the source code was last updated on 2024-09-20. What is the difference between the store version and the open-source version?

商店图标

**Comment by startle09** [comment]
谢谢，插件很好用！
